name: Deploy to VPS

on:
  push:
    branches:
      - developer
      - staging  # Lắng nghe cả 2 nhánh

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          # Kiểm tra nhánh đang push để chọn Host tương ứng
          host: ${{ github.ref_name == 'developer' && secrets.DEV_HOST || secrets.STAGING_HOST }}
          username: ${{ github.ref_name == 'developer' && secrets.DEV_USERNAME || secrets.STAGING_USERNAME }}
          key: ${{ github.ref_name == 'developer' && secrets.DEV_SSH_KEY || secrets.STAGING_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            cd /var/www/ims-server
            git pull origin ${{ github.ref_name }}
            npm install
            npm run build
            pm2 restart ims-server
            sudo systemctl reload nginx